- name: Install service httpd on machines
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install service apache2
      yum:
        name: apache2
        state: latest
        update_cache: yes

    - name: Start service apache2
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Upgrade index.html
      template:
        src: index.html
        dest: "/var/www/html/index.html"
        mode: '0755'