- name: Create environment to deploy an load balancer and VMs from scratch
  hosts: localhost
  gather_facts: false
  connection: local
  
  vars:
    resource_group: myResourceGroup
    vmss_name: myScaleSet
    vmss_lb_name: myScaleSetLb
    location: eastus
    webserver: webserver
    admin_username: azureuser
    image_name: "image_target"

  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        address_prefix: "10.0.0.32/27"
        virtual_network: "{{ vmss_name }}"

    - name: Get webserver info
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
        tags:
          - Name:"{{ webserver }}"
      register: __webserver_info

    - name: Create web-server1 machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ webserver }}"
        admin_username: "{{ admin_username }}"
        vm_size: Standard_B1ls
        virtual_network_name: "{{ vmss_name }}"
        public_ip_allocation_method: Static
        ssh_password_enabled: False
        ssh_public_keys: 
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCNt/oVfP6RoPwn7WB0cytqsmsVdRK1ZF66k3LO9W1UA4msGx8J9Ifoe+arBPsdtUBGaCCBFkuvnjC2+eMAaBGsfCOXkcuwNQwb2TEg8C9yyebY4JWFfbyzwSMnUHczdW/xXlf5CEQhwPu/jdDYrOKeoeTRZB5xjJoje/So6WQkRRohZQme4SmU7d/K4BcLHwwREiC9ipammTqpOycdfP1EnKqVVhe7DnJk0YESkmbVNDHk+EDKLEmral4TaMxPShR0rItV/qcuemwVkcQ6uEPN0sinJE3w36xNyVuJ3VQ8H4RrPaj1Vi5Xqxcn1PJe3ZRMD5wN4B0Jg3e6tMoRsj+OX1sTH3BWoHVAaCxycp1ZWQWfAc/nAcn1xQAlQJgS8niXsphFXNx7UnelzjsdC4yvTLyjuZ1hKNXJTmBdmu2y14xxfZhJmDBV6cGfgloBa+odCJunHKFYKhtwq65LB8qYh/bBBx8S4kjoC9L4wq2fdMmJrOMfcYsIMWjygqHW2u0= generated-by-azure'
        open_ports:
          - 22
          - 80
        tags:
          Name: "{{ webserver }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: '18.04-LTS'
          version: latest
      when: __webserver_info.vms|length == 0

    - name: Wait for connection
      pause:
        minutes: 1

    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory