- name: Deploy an load balancer and auto scale
  hosts: localhost
  gather_facts: false
  
  vars:
    resource_group: myResourceGroup
    vmss_name: myScaleSet
    vmss_lb_name: myScaleSetLb
    location: eastus
    webserver: webserver
    admin_username: azureuser
    image_name: "image_target"

  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        allocation_method: Static
        name: "{{ vmss_name }}"
      register: pip_output

    - name: Stop and generalize VMs
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ webserver }}"
        generalized: yes

    - name: Create an images from a VMs
      azure_rm_image:
        resource_group: "{{ resource_group }}"
        name: "image_target"
        source: "{{ webserver }}"

    - name: Create Network Security Group that allows SSH
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound

    - name: Create a load balancer
      azure_rm_loadbalancer:
        name: "{{ vmss_lb_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        public_ip: "{{ vmss_name }}"
        probe_protocol: Tcp
        probe_port: 80
        probe_interval: 10
        probe_fail_count: 3
        protocol: Tcp
        load_distribution: Default
        frontend_port: 80
        backend_port: 80
        idle_timeout: 4
        natpool_frontend_port_start: 50000
        natpool_frontend_port_end: 50040
        natpool_backend_port: 22
        natpool_protocol: Tcp

    - name: Create a scale set
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: "{{ vmss_name }}"
        vm_size: Standard_DS1_v2
        admin_username: "{{ admin_username }}"
        ssh_password_enabled: False
        ssh_public_keys: 
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCNt/oVfP6RoPwn7WB0cytqsmsVdRK1ZF66k3LO9W1UA4msGx8J9Ifoe+arBPsdtUBGaCCBFkuvnjC2+eMAaBGsfCOXkcuwNQwb2TEg8C9yyebY4JWFfbyzwSMnUHczdW/xXlf5CEQhwPu/jdDYrOKeoeTRZB5xjJoje/So6WQkRRohZQme4SmU7d/K4BcLHwwREiC9ipammTqpOycdfP1EnKqVVhe7DnJk0YESkmbVNDHk+EDKLEmral4TaMxPShR0rItV/qcuemwVkcQ6uEPN0sinJE3w36xNyVuJ3VQ8H4RrPaj1Vi5Xqxcn1PJe3ZRMD5wN4B0Jg3e6tMoRsj+OX1sTH3BWoHVAaCxycp1ZWQWfAc/nAcn1xQAlQJgS8niXsphFXNx7UnelzjsdC4yvTLyjuZ1hKNXJTmBdmu2y14xxfZhJmDBV6cGfgloBa+odCJunHKFYKhtwq65LB8qYh/bBBx8S4kjoC9L4wq2fdMmJrOMfcYsIMWjygqHW2u0= generated-by-azure'
        capacity: 2
        virtual_network_name: "{{ vmss_name }}"
        subnet_name: "{{ vmss_name }}"
        upgrade_policy: Manual
        tier: Standard
        managed_disk_type: Standard_LRS
        os_disk_caching: ReadWrite
        image:
          name: "{{ image_name }}"
          resource_group: "{{ resource_group }}"
        load_balancer: "{{ vmss_name }}lb"

    - debug:
        msg: "Scale set public IP address: {{ pip_output.state.ip_address }}"