- name: Delete all environment
  hosts: localhost
  gather_facts: false
  vars:
    resource_group: myResourceGroup

  tasks:
  - name: Delete a resource group including resources it contains
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      force_delete_nonempty: yes
      state: absent